name: close release issue

on:
  workflow_run:
    workflows: [release]
    branches:
      - main
    types:
      - completed

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  closeIssue:
      name: Close release issue
      runs-on: ubuntu-latest
      steps:
        - name: Find issues
          id: release-issue
          run: |
            echo "$REPO"
            releaseIssue="$(gh search issues --repo=$REPO --state=open --label=notify-release)"
            releaseIssuee="$(gh search issues --repo=$REPO --state=open --label=notify-release | jq 'keys')"
            echo "::set-output name=issue::$releaseIssue"
            echo "$releaseIssuee"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO: ${{ github.repository }}
        # - name: Close release issues
        #   run: cat ${{ steps.release-issue.outputs.issue }} | xargs gh issue close
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
