name: close release issue

on:
  workflow_run:
    workflows: [release]
    branches:
      - main
      - master
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: ${{ github.repository }}

jobs:
  closeIssue:
      name: Close release issue
      runs-on: ubuntu-latest
      steps:
        - name: Find issues
          id: release-issue
          run: |
            issueNumber="$(gh search issues --repo=$REPO --state=open --label=notify-release --json=number | jq -r '.[0].number')"
            echo "::set-output name=issue::$issueNumber"
        - name: Close release issues
          run: |
            gh issue close --repo=$REPO "$ISSUE_NUMBER"
          env:
            ISSUE_NUMBER: ${{ steps.release-issue.outputs.issue }}
