name: close release issue

on:
  workflow_run:
    workflows: [release]
    types:
      - completed

jobs:
  closeIssue:
      name: Close issue created by notify-release
      runs-on: ubuntu-latest
      steps:
        - name: Find release issue
          id: release-issue
          uses: lee-dohm/select-matching-issues@v1
          with:
            format: list
            query: 'label:notify-release is:open'
            token: ${{ github.token }}
        - name: Close release issues
          run: cat ${{ steps.release-issue.outputs.path }} | xargs gh issue close
