name: close release issue

# on:
#   workflow_run:
#     workflows: [release]
#     branches:
#       - main
#       - master
#     types:
#       - completed

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: false
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  closeIssue:
      name: Close release issue
      runs-on: ubuntu-latest
      steps:
        - name: Find issues
          id: release-issue
          run: |
            echo "$REPO"
            releaseIssue="$(gh search issues --repo=$REPO --state=open --label=notify-release --json=title | jq -r '.[0]')"
            echo "::set-output name=issue::$releaseIssue"
            echo "$releaseIssue"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO: ${{ github.repository }}
        - name: Close release issues
          run: cat ${{ steps.release-issue.outputs.issue.number }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  | xargs gh issue close