name: close release issue

on:
  workflow_run:
    workflows: [release]
    branches:
      - main
    types:
      - completed

jobs:
  closeIssue:
      name: Close release issue
      runs-on: ubuntu-latest
      steps:
        - name: Find issues
          id: release-issue
          run: |
            releaseIssue="$(gh search issues --label:notify-release)"
            echo "::set-output name=issue::$releaseIssue"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Close release issues
          run: cat ${{ steps.release-issue.outputs.issue }} | xargs gh issue close
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
