name: close release issue

on:
  workflow_run:
    workflows: [release]
    types:
      - completed

jobs:
  closeIssue:
      name: Close issue created by notify-release
      runs-on: ubuntu-latest
      steps:
        - name: Find issues
          id: release-issue
          uses: actions-cool/issues-helper@v3
          with:
            actions: 'find-issues'
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-creator: 'github-actions'
            issue-state: 'open'
            title-includes: 'Release pending!'
            body-includes: 'Pending commits since release'
            labels: 'notify-release'
        - name: Close release issues
          run: cat ${{ steps.release-issue.outputs.path }} | xargs gh issue close
