name: close release issue

on:
  workflow_run:
    workflows: [release]
    branches:
      - main
    types:
      - completed

jobs:
  closeIssue:
      name: Close release issue
      runs-on: ubuntu-latest
      steps:
        - name: Find issues
          id: release-issue
          run: |
            releaseIssue="$(gh search issues --repo=$REPO --owner=$OWNER --state=open --label=notify-release | jq -r '.[] | .title')"
            echo "::set-output name=issue::$releaseIssue"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
        # - name: Close release issues
        #   run: cat ${{ steps.release-issue.outputs.issue }} | xargs gh issue close
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
