name: notify-release
on:
  workflow_dispatch:
  release:
    types: [published]
    branches:
      - main
  release:
    types: [published]
  schedule:
    - cron: '30 8 * * *'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check if there's a release pending
        id: notify
        uses: nearform/github-action-notify-release@main
        with:
          stale-days: 0
