name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Node.js runtime on build
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: sameer-coder/optic-release-automation-action@main
        with:
          github-token: ${{ github.token }}
          semver: ${{ github.event.inputs.semver }}
          sync-semver-tags: true
          build-command: |
            echo 'installing husky hooks..'
            npm ci
